### ISSUE TITLE
Does not work within a Spring CommandLineRunner

### ISSUE THREAD

**Issue by fanalin** [vbauer/herald#1]
When creating a logger inside a CommandLineRunner class from Spring, the @Log annotation does not inject a logger.

**Comment by vbauer** [comment]
I've just release version 1.2.0. It has integration with Spring Boot (see `LogAutoConfiguration`), so it is unnecessary to have the following block of code in your configuration:

```java
    @Bean
    public LogBeanPostProcessor logBeanPostProcessor() {
        return new LogBeanPostProcessor();
    }
```

Also I added unit test to check `ApplicationRunner` and `CommandLineRunner`. Everything looks fine. Tell me if something is wrong.
