### ISSUE TITLE
Unable to use @Log annotation in Spring boot 1.4.2

### ISSUE THREAD

**Issue by harishreddy-m** [vbauer/herald#2]
https://github.com/harishreddy-m/base

Steps to reproduce:
Run HelloControllerTest Junit test.

**Comment by vbauer** [comment]
As I see, there is no bug in Herald. I sent you PR to show the problem in unit tests: https://github.com/harishreddy-m/base/pull/1

**Explanation:**

* `HelloControllerTest` marks with `@RunWith(SpringRunner.class)`. It is not a Spring Boot test, so auto-configurations (`com.github.vbauer.herald.ext.spring.LogAutoConfiguration`) not works.
* `CloudinaryClientTest` marks with annotation `@SpringBootTest`, so Spring Boot's auto-configurations work in this class.
